#!/bin/bash

# Test extraction of loops from C code.
# Dump them to a file named initial_fragments.dump, and open it in gedit.

# Recompile the relevant Txl programs.
RELEVANT_TXL_PROGRAMS="c-extract-loops.txl"
cd txl;
if ! txlc $RELEVANT_TXL_PROGRAMS; then
    cd ..; exit
fi
cd ..;

./cwbuild   --input             example/NPB3.4.1/                \
            --fileids           example/NPB.files                \
            --code-fragments    example/NPB.fragments            \
            --language          c                                \
            --granularity       loop                             \
            --configuration     fragment_extraction_test         \
&&
./cwdetect  --input             example/NPB.fragments            \
            --output            example/NPB.clones               \
            --min-similarity    0.8                              \
&&
./cwformat  --fileids           example/NPB.files                \
            --clones            example/NPB.clones               \
            --output            example/NPB.clones.pretty        \
            --formater          xml_withsrc                      \
&& gedit initial_fragments.dump
# TODO: experiment with other values for --formater and formatter options
