#!/bin/bash

./cwbuild   --input             example/NPB3.4.1/                \
            --fileids           example/NPB.files                \
            --code-fragments    example/NPB.fragments            \
            --language          c                                \
            --granularity       block                            \
            --configuration     loop_granularity_test            \
&&
./cwdetect  --input             example/NPB.fragments            \
            --output            example/NPB.clones               \
            --min-similarity    0.8                              \
&&
./cwformat  --fileids           example/NPB.files                \
            --clones            example/NPB.clones               \
            --output            example/NPB.clones.pretty        \
            --formater          xml_withsrc                      \
# TODO: experiment with other values for --formater and formatter options
